# Generated by Django 6.0.4 on 2026-04-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=150, verbose_name='Nombre y apellido')),
                ('whatsapp', models.CharField(max_length=30, verbose_name='WhatsApp / Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('pais_ciudad', models.CharField(max_length=120, verbose_name='País y ciudad de residencia')),
                ('tiene_visa', models.CharField(choices=[('visa_usa', 'Visa USA'), ('ciudadania', 'Ciudadanía'), ('ninguna', 'Ninguna'), ('otro', 'Otro')], max_length=20, verbose_name='¿Tenés visa o ciudadanía?')),
                ('destino', models.CharField(choices=[('disney_orlando', 'Disney Orlando'), ('disney_paris', 'Disney París'), ('disney_tokio', 'Disney Tokio'), ('universal', 'Universal Orlando'), ('miami', 'Miami'), ('europa', 'Europa'), ('crucero', 'Crucero'), ('otro', 'Otro')], max_length=30, verbose_name='¿A dónde pensás viajar?')),
                ('destino_otro', models.CharField(blank=True, max_length=120, verbose_name='Otro destino (especificar)')),
                ('multidestino', models.CharField(blank=True, max_length=200, verbose_name='¿Querés más de un destino?')),
                ('preferencia_hotel', models.TextField(blank=True, verbose_name='Preferencia de hotel (Disney/Universal)')),
                ('fecha_salida', models.DateField(verbose_name='Fecha tentativa de salida')),
                ('flexibilidad_fechas', models.CharField(choices=[('flexible', 'Sí, una semana antes/después'), ('fija', 'No, son fechas fijas')], max_length=20, verbose_name='¿Tenés flexibilidad de fechas?')),
                ('cantidad_noches', models.PositiveSmallIntegerField(verbose_name='Cantidad de noches previstas')),
                ('adultos', models.PositiveSmallIntegerField(verbose_name='Cantidad de adultos (18+)')),
                ('menores', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad de menores')),
                ('edades_menores', models.CharField(blank=True, max_length=200, verbose_name='Edades de los menores')),
                ('incluir_vuelos', models.BooleanField(default=False, verbose_name='¿Incluir vuelos en el presupuesto?')),
                ('necesita_traslados', models.BooleanField(default=False, verbose_name='¿Necesita auto/traslados privados?')),
                ('dias_parques', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Días de parques en Orlando')),
                ('asesoria_visa', models.BooleanField(default=False, verbose_name='¿Necesita asesoría de visa/ESTA/ETIAS?')),
                ('presupuesto', models.CharField(blank=True, max_length=100, verbose_name='Presupuesto estimado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Contanos más sobre tu viaje ideal')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
