# Generated by Django 6.0.4 on 2026-04-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='fecha_turno',
            field=models.DateField(blank=True, null=True, verbose_name='Día del turno'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora_turno',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario del turno'),
        ),
    ]
