# Generated by Django 6.0.4 on 2026-04-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_consulta_fecha_turno_consulta_hora_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_turno',
            field=models.DateField(default='2026-01-01', verbose_name='Día del turno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hora_turno',
            field=models.TimeField(default='00:00', verbose_name='Horario del turno'),
            preserve_default=False,
        ),
    ]
