# Generated by Django 6.0.4 on 2026-04-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_consulta_fecha_turno_alter_consulta_hora_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('cotizacion', 'Cotización'), ('confirmacion', 'Confirmación'), ('reserva', 'Reserva'), ('pago_completado', 'Pago completado'), ('filas_rapidas', 'Sacar filas rápidas'), ('itinerario', 'Hacer itinerario'), ('reunion_pre', 'Reunión pre viaje'), ('en_viaje', 'En destino / En viaje')], max_length=20, null=True, verbose_name='Etiqueta'),
        ),
    ]
