# Generated by Django 6.0.4 on 2026-04-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_consulta_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='servicio',
            field=models.CharField(choices=[('cotizacion_paquete', 'Cotización de paquete completo'), ('asesoramiento', 'Asesoramiento (ya tengo todo sacado)'), ('reserva_alojamiento', 'Reserva de alojamiento'), ('vuelos_vehiculos', 'Vuelos y vehículos'), ('otro', 'Otro')], default='cotizacion_paquete', max_length=30, verbose_name='Servicio que desea contratar'),
            preserve_default=False,
        ),
    ]
